# Generated by Django 4.0.4 on 2022-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='unset', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='none', max_length=200),
        ),
    ]
